spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ScaleApps
    username: postgres
    password: postgres



  liquibase:
    change-log: db/changelog/master-changelog.xml



  jpa:
    hibernate:
      ddl-auto: validate
#      show-sql: true




#prod:
#  mode: true


#logging:
#  level:
#    root: info
